GET http://localhost:5022/Hello

###
#
GET http://localhost:5022/daysbetweendates?startDate=2020-01-01&enddate=2020-01-10

###
GET http://localhost:5022/validateemail?email=test@example.com


###
Get http://localhost:5022/openid


###
get http://localhost:5022/parseurl?url=https://www.google.com?param=param1

###
Get http://localhost:5022/joke


###
get http://localhost:5022/randomeuropeancountry



###
get http://localhost:5022/memoryusage

###
Get http://localhost:5022/files


###
Get http://localhost:5022/parallelloop?iteration=002
